//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Administrator
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Tài khoản không được bỏ trống")]
        public string Username { get; set; }
        [Required(ErrorMessage ="Mật khẩu không được bỏ trống")]
        public string Password { get; set; }
    }
}
