//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema
    {
        public int IDMovie { get; set; }
        public string NameMovie { get; set; }
        public string Director { get; set; }
        public int Ticket { get; set; }
    }
}
