//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int Id { get; set; }
        public int id_member { get; set; }
        public int id_movie { get; set; }
        public System.DateTime date_buy { get; set; }
        public int amount { get; set; }
        public int prices { get; set; }
    }
}
